### ISSUE TITLE
can't suspend watching

### ISSUE THREAD

**Issue by spencerparkin** [gorakhargosh/watchdog#438]
An editor program wants to watch the file it's editing so that it can reload that file if it is changed externally.  But what if that same editor program wants to save the file?  In that case, it doesn't want the watchdog observer to get triggered.  Is there any way to suspend watching?  I've tried turning off the watcher, saving, and then turning it back on, but as soon as the watching is turned back on, a notification is fired.

**Comment by danilobellini** [comment]
How did you *suspend* and *turn it back on*?
How much time did you wait between these?

Perhaps you should just ignore the first fired notification in this case, instead of suspending the watcher. Maybe you're really suspending, but the file saving procedure might happen to be deferred, so that it actually saved your file after you've turned the watcher back on. Anyway, it's hard to tell what's going on without some actual code.
