### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [gorakhargosh/watchdog#460]
The latest version on PyPI is 0.9.0, but [changelog.rst](https://github.com/gorakhargosh/watchdog/blob/master/changelog.rst) is only up to 0.8.2.

**Comment by danilobellini** [comment]
You're right, but I think this issue shouldn't be closed until we get a full changelog, not just one regarding v0.9.0.

The changelog is outdated since long ago (v0.8.3 was released 2015-02-11), but it's not just outdated, it's incomplete. It was never written as a comprehensive changelog, and having one would probably be quite helpful (e.g. to know when a major bug fix happened, when a Python version support had been dropped, when a new feature appeared, etc.), though most people will probably just rely on the last release.

**Comment by BoboTiG** [comment]
I updated the changelog into #461. I think this is good enough now, we do not need to go back too far in the releases as they are totally outdated.
Do you see something missing @danilobellini?

**Comment by danilobellini** [comment]
Actually, the changelog isn't just about a version but also about what had already happened in the project.

The changelog regarding the oldest versions doesn't need be emphasized, but I think we should at least write a summary regarding everything that happened since v0.8.3.

For older versions, a further analysis to create a changelog is useful to see in the code if something is broken/missing because someone started something but didn't finish, besides creating a throughout documentation.
