### ISSUE TITLE
For python 3.7, we should use collections.abc.MutableSet

### ISSUE THREAD

**Issue by AdrienPensart** [gorakhargosh/watchdog#486]
/home/crunch/.cache/pypoetry/virtualenvs/musicbot-py3.7/lib/python3.7/site-packages/watchdog/utils/bricks.py:175: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class OrderedSet(collections.MutableSet):

Simple fix : use collections.abc.MutableSet

**Comment by AdrienPensart** [comment]
Oups, already fixed in master !

**Comment by hkiang01** [comment]
This warning is present in 0.9.0.

**Comment by hkiang01** [comment]
Here is the fix: https://github.com/gorakhargosh/watchdog/commit/152d3f8800f9e111e5477207ecc60b08e7dcd42d#diff-1fc0dfc77c8110671a21b65dc4b42543R178

**Comment by hkiang01** [comment]
This warning is present in 0.9.0, which is the current version at time of typing:
![image](https://user-images.githubusercontent.com/5448093/52675636-6f426c00-2ef5-11e9-838a-2bfcedcc135a.png)
https://pypi.org/project/watchdog/#history

Note that 0.9.0 was released on Aug 28, 2018. The fix was implemented on Sep 10, 2018 (see  https://github.com/gorakhargosh/watchdog/commit/69871314de0e5d8422c070bc91fed26ed5ce94a0#diff-1fc0dfc77c8110671a21b65dc4b42543R179)

**Comment by hkiang01** [comment]
It doesn't look like there's another release yet. See https://github.com/gorakhargosh/watchdog/issues/485
