### ISSUE TITLE
Suppress watchmedo on_any_event log messages

### ISSUE THREAD

**Issue by garyns** [gorakhargosh/watchdog#594]
When using watchmedo auto-restart how can I suppress all the event messages logged to the console? It's noise I do not want to see. 

Thanks.

Eg:
```shell
$ watchmedo auto-restart test.sh
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0xb634ab30>, event=<FileCreatedEvent: src_path='./4913'>)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0xb634ab30>, event=<DirModifiedEvent: src_path='.'>)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0xb634ab30>, event=<FileModifiedEvent: src_path='./4913'>)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0xb634ab30>, event=<FileDeletedEvent: src_path='./4913'>)
on_any_event(self=<watchdog.tricks.AutoRestartTrick object at 0xb634ab30>, event=<DirModifiedEvent: src_path='.'>)
```

**Comment by danilobellini** [comment]
As of today, there's no way, because of the `watchdog.utils.echo.echo` decorator applied on the `watchdog.tricks.AutoRestartTrick.on_any_event` method. This decorator writes unconditionally to `stdout`. A path to solve this issue would be:

- [ ] Add `-v`/`-vv` verbosity mode (show `INFO`/`DEBUG`) and `-q`/`--quiet` (hide `WARNING`) options to all watchmedo commands;
- [ ] Let all "echo" functions in `utils` accept a logger from `logging` instead of a file object;
- [ ] Make all `watchmedo` commands use the "echo" functions with a logger instead of `stdout`. The new logger should write to `stderr` instead of `stdout`.

I wonder how many people use the `watchdog.utils.echo` module, it's mostly part of the watchmedo, but that proposed change can be done without breaking the current behavior of those functions.

**Comment by and3rson** [comment]
Is this still planned? I've been using `watchmedo` for a long time, but those log messages are really spamming entire output, making it hard to visually find any relevant logs.

**Comment by BoboTiG** [comment]
Nothing is planed, but PRs are very welcome :)
