### ISSUE TITLE
SystemError with Spyder

### ISSUE THREAD

**Issue by BoboTiG** [gorakhargosh/watchdog#765]
See https://github.com/spyder-ide/spyder/issues/14779, there is definitively something not well handled in watchdog:
```python
  File "/.../observers/fsevents.py", line 283, in run
    _fsevents.add_watch(self, self.watch, callback, self.pathnames)
SystemError: <built-in function add_watch> returned NULL without setting an error
```

cc @CCP-Aporia & @SamSchott, I did not test on my side, but will find time the next week hopefully.

**Comment by SamSchott** [comment]
It looks like there are two situations in which `add_watch` can possibly return NULL without setting an error.

When creating a PyCapsule with the stream reference:

https://github.com/gorakhargosh/watchdog/blob/4c37723b3c040b619c6431242b2823d20a1e44be/src/watchdog_fsevents.c#L653-L658

This code is new in v1.0.0 (one of @CCP-Aporia's changes?) so it might be the issue. But according to the Python docs `PyCapsule_New` will set an exception when it fails.

https://github.com/gorakhargosh/watchdog/blob/4c37723b3c040b619c6431242b2823d20a1e44be/src/watchdog_fsevents.c#L688-L693

This code already existed pre v1.0.0 but `FSEventStreamStart` may be failing now due to other changes.

Maybe the first step is to explicitly raise errors in both cases and see if we can reproduce the issue from Spyder.

**Comment by CCP-Aporia** [comment]
The `FSEventStreamStart` check quoted above is certainly missing a corresponding `PyErr_SetString` call. But also, so is this line which checks if a duplicate watch is added: https://github.com/gorakhargosh/watchdog/blob/4c37723b3c040b619c6431242b2823d20a1e44be/src/watchdog_fsevents.c#L637
PR submitted to address these cases. The `PyCapsule_*` calls should be setting their exception already.

**Comment by BoboTiG** [comment]
Well, it is worth a new minor release: v2.0.2.
