### ISSUE TITLE
[Mac] FSEvents handler ignores the 'recursive' parameter

### ISSUE THREAD

**Issue by m-koopman** [gorakhargosh/watchdog#771]
When attaching a `FileSystemEventHandler` with the `schedule` method on MacOS, the recursive flag appears to be ignored on the latest versions of watchdog. 

Regardless of the value, it is acting recursively. My expected behaviour was that if I have a tree like
```
a/
   b/
      c.d
```
And I call `observer.schedule(my_handler, 'a', recursive=False)`, the handler would not be notified on changes to the `c.d` file. 

Searching back, the latest version that respected that flag matching the expectations above was 0.10.3.

**Comment by BoboTiG** [comment]
cc @CCP-Aporia and @SamSchott, does it ring a bell to anyone of you?

**Comment by CCP-Aporia** [comment]
Indeed, `fsevents` is always recursive since the OS functionality doesn't support non-recursive notifications. That said, we could of course add that functionality in by simply discarding those events which aren't matching the provided watch. I guess this used to work before 0.10.3 due to the directory snapshots that were used instead of `fseventsd`. I'll see if I can get around to it this week.

**Comment by BoboTiG** [comment]
Oh that makes sense!
