### ISSUE TITLE
Passing argument in on_created

### ISSUE THREAD

**Issue by comand100vip** [gorakhargosh/watchdog#827]
I am creating some kind of sorter,
the ptoblem is that then on_create function is called by watchdog I had to pass conf_file and data arguments, but how?
I was searching in internet and documentation, but I didn't find a wat to do that.

code:
```
def handler(self, conf_file):
    data = load_json(conf_file, "r")  # I load json file and later I want pass it to function
    path = f"{current_dir()}/{data['input_folder']}"
    event_handler = LoggingEventHandler()
    event_handler.on_created = self.on_created  # here I want pass conf_file and data
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
```

**Comment by orgarten** [comment]
In case you still have this problem, you can write your own Handler class that which takes the configuration in its `__init__` function and implement your own on_created which uses the configuration.

```
class YourHandler(FileSystemEventHandler):
  def __init__(self, config):
    super().__init__()
    self.config = config

  def on_created(self, event):
    if self.config:
      ....
```

In `handler` you then use `event_handler = YourEventHandler(config)` 

Instead of FileSystemEventHandler you probably can inherit from LoggingEventHandler and only override the on_created method.

**Comment by comand100vip** [comment]
Ohh sorry I just forget to close this issue.
