### ISSUE TITLE
watchmedo auto-restart behavior change with 2.1.9

### ISSUE THREAD

**Issue by jaycle** [gorakhargosh/watchdog#922]
We were using `watchmedo auto-restart` to call mypy and some flake8 tooling upon file changes. With the changes introduced by https://github.com/gorakhargosh/watchdog/pull/896, these processes re-run continually every time they exit whereas before they were re-ran upon a watched file/directory change.

The name `auto-restart` makes me believe that this is actually desirable behavior and perhaps we were misusing that sub-command, however there doesn't appear to be an alternative to get the behavior we once had. `watchmedo shell-command` only runs the command on change with no option to run it once _and also_ upon watched file change.

Is there a way to add a flag to `auto-restart` which only restarts on an exit code, or maybe a way to use `shell-command` to call the command initially and then repeat on a file change?

**Comment by taleinat** [comment]
This seems like it would be simple to implement with a script, which would run the tools once initially and then call `watchmedo shell-command ...`. I'm not sure it's worth changing `watchmedo` to support it.

BTW, this seems like a great use-case for grouping together multiple events happening in a short time-frame (a.k.a .debouncing) and launching the command only after that, similar to #542. This was implemented for `watchmedo auto-restart` in PR #940. If you'd like this for `watchmedo shell-command` too, consider creating an issue requesting that!

**Comment by adamzev** [comment]
Running the tools once initially and then calling `watchmedo shell-command` doesn't produce equivalent behavior for our use case. `watchmedo auto-restart` is often recommended to relaunch celery on file changes. However with the changes introduced by https://github.com/gorakhargosh/watchdog/pull/896,celery it continually restart on errors (which causes issues with our error logs getting flooded). If we launch celery and then call `watchmedo shell-command` it wouldn't be able to restart celery for us since that was started separately. I'm sure we could create workarounds for this but not with the same simplicity as before.

Could we get a flag to disable (or enable, depending on what you want as the default) the following two lines?
```
# src/watchdog/tricks/__init__.py
self.process_watcher = ProcessWatcher(self.process, self._restart)
self.process_watcher.start()
```

**Comment by taleinat** [comment]
@BoboTiG WDYT? We could add a flag for the trick and the CLI command.

**Comment by BoboTiG** [comment]
@taleinat yup, that would be a simple solution 👍

**Comment by BoboTiG** [comment]
Thanks a lot @taleinat !

I'll see to cut a new release iin the week.

**Comment by BoboTiG** [comment]
[v2.3.0](https://github.com/gorakhargosh/watchdog/releases/tag/v2.3.0) is out :champagne:
